export const GROUP_ROLE = { OWNER: "OWNER", MEMBER: "MEMBER" };
export const RECEIPT_STATUS = { PENDING: "PENDING", VERIFIED: "VERIFIED", REJECTED: "REJECTED" };
export const PAYMENT_STATUS = { PENDING: "PENDING", CONFIRMED: "CONFIRMED", REJECTED: "REJECTED" };
